version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5001:5000"
    env_file:
      - .env
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=5000
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cashcoach
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
